// Application
export const INITIALIZE_APP = 'initializeApp'
export const OPEN_NAVIGATION = 'openNavigation'
export const CLOSE_NAVIGATION = 'closeNavigation'
export const SET_SAVED_SCROLL_POSITION = 'setSavedScrollPosition'
export const UNSET_SAVED_SCROLL_POSITION = 'unsetSavedScrollPosition'

// API
export const SET_API_STATUS = 'setApiStatus'
export const SET_API_INFO = 'setApiInfo'

// Authentication
export const SET_USER = 'setUser'
export const UNSET_USER = 'unsetUser'
export const AUTHORIZE = 'authorize'
export const DEAUTHORIZE = 'deauthorize'
export const SET_AUTHORIZING = 'setAuthorizing'
export const UNSET_AUTHORIZING = 'unsetAuthorizing'
export const SET_CREATING_USER = 'setCreatingUser'
export const UNSET_CREATING_USER = 'unsetCreatingUser'
export const SET_UPDATING_USERNAME = 'setUpdatingUsername'
export const UNSET_UPDATING_USERNAME = 'unsetUpdatingUsername'
export const SET_UPDATED_USERNAME = 'setUpdatedUsername'
export const UNSET_UPDATED_USERNAME = 'unsetUpdatedUsername'
export const SET_UPDATING_PASSWORD = 'setUpdatingPassword'
export const UNSET_UPDATING_PASSWORD = 'unsetUpdatingPassword'
export const SET_UPDATED_PASSWORD = 'setUpdatedPassword'
export const UNSET_UPDATED_PASSWORD = 'unsetUpdatedPassword'
export const SET_DELETING_USER = 'setDeletingUser'
export const UNSET_DELETING_USER = 'unsetDeletingUser'

// Error
export const RAISE = 'raise'
export const FLUSH = 'flush'

// Tags
export const SET_TAGS_LOADING = 'setTagsLoading'
export const UNSET_TAGS_LOADING = 'unsetTagsLoading'
export const SET_TAGS = 'setTags'
export const APPEND_TAGS = 'appendTags'
export const UNSET_TAGS = 'unsetTags'
export const SET_LAST_TAGS_QUERY = 'setLastTagsQuery'
export const UNSET_LAST_TAGS_QUERY = 'unsetLastTagsQuery'
export const SET_TOTAL_TAG_COUNT = 'setTotalTagCount'
export const UNSET_TOTAL_TAG_COUNT = 'unsetTotalTagCount'
export const SET_LAST_TAGS_PAGE_REACHED = 'setLastTagsPageReached'
export const UNSET_LAST_TAGS_PAGE_REACHED = 'unsetLastTagsPageReached'
export const SET_NAMESPACES = 'setNamespaces'

// Files
export const SET_FILES_LOADING = 'setFilesLoading'
export const UNSET_FILES_LOADING = 'unsetFilesLoading'
export const SET_FILES = 'setFiles'
export const APPEND_FILES = 'appendFiles'
export const UNSET_FILES = 'unsetFiles'
export const SET_LAST_FILES_QUERY = 'setLastFilesQuery'
export const UNSET_LAST_FILES_QUERY = 'unsetLastFilesQuery'
export const SET_TOTAL_FILE_COUNT = 'setTotalFileCount'
export const UNSET_TOTAL_FILE_COUNT = 'unsetTotalFileCount'
export const SET_LAST_FILES_PAGE_REACHED = 'setLastFilesPageReached'
export const UNSET_LAST_FILES_PAGE_REACHED = 'unsetLastFilesPageReached'
export const SET_DETAIL_ITEM = 'setFileDetailItem'
export const UNSET_DETAIL_ITEM = 'unsetFileDetailItem'
export const SET_LAST_DETAIL_ID = 'setLastFileDetailId'
export const SET_MIME_TYPES = 'setMimeTypes'

// Settings
export const SET_RESTRICT_IMAGE_SIZE = 'setRestrictImageSize'
export const SET_COLORS = 'setColors'
export const SET_FILES_SORTING = 'setFilesSorting'
export const SET_FILES_SORTING_DIRECTION = 'setFilesSortingDirection'
export const SET_FILES_SORTING_NAMESPACES = 'setFilesSortingNamespaces'
export const SET_TAGS_SORTING = 'setTagsSorting'
export const SET_TAGS_SORTING_DIRECTION = 'setTagsSortingDirection'
